import { useState, useEffect } from "react";
import { useAuth } from "../../context/AuthContext";
import { billService } from "../../services/billService";
import { Receipt, CreditCard, ChevronLeft, CheckCircle2, Clock, AlertCircle } from "lucide-react";
import { Card } from "../../components/ui/Card";
import Button from "../../components/ui/Button";
import { motion, AnimatePresence } from "framer-motion";
import { useNavigate } from "react-router-dom";
import { collection, query, where, onSnapshot, orderBy } from "firebase/firestore";
import { db } from "../../config/firebase";

const BillsPage = () => {
    const { currentUser } = useAuth();
    const [bills, setBills] = useState([]);
    const [loading, setLoading] = useState(true);
    const navigate = useNavigate();

    useEffect(() => {
        if (!currentUser) {
            setLoading(false);
            return;
        }

        // Real-time listener for user's bills
        const q = query(
            collection(db, "bills"),
            // Use either userId or phone as a fallback if userId wasn't set by admin
            where("userId", "==", currentUser.uid),
            orderBy("timestamp", "desc")
        );

        const unsubscribe = onSnapshot(q, (snapshot) => {
            const billsData = snapshot.docs.map(doc => ({
                id: doc.id,
                ...doc.data()
            }));
            setBills(billsData);
            setLoading(false);
        }, (error) => {
            console.error("Error fetching bills:", error);
            setLoading(false);
        });

        return () => unsubscribe();
    }, [currentUser]);

    const handlePayment = async (bill) => {
        // Simulate Payment process
        try {
            const confirmPay = window.confirm(`Proceed to pay ₹${bill.total}?`);
            if (!confirmPay) return;

            // In a real app, you'd trigger Razorpay here
            // For now, we simulate success
            const mockPaymentId = "PAY_" + Math.random().toString(36).substr(2, 9).toUpperCase();
            await billService.markAsPaid(bill.id, mockPaymentId);
            alert("Payment successful! Receipt sent to your email.");
        } catch (error) {
            console.error("Payment failed:", error);
            alert("Payment failed. Please try again.");
        }
    };

    if (loading) {
        return (
            <div className="min-h-screen flex items-center justify-center bg-background">
                <div className="w-12 h-12 border-4 border-saffron border-t-transparent rounded-full animate-spin" />
            </div>
        );
    }

    if (!currentUser) {
        return (
            <div className="min-h-screen flex flex-col items-center justify-center p-8 text-center bg-background">
                <div className="w-20 h-20 bg-charcoal/50 rounded-3xl flex items-center justify-center mb-6 border border-white/5">
                    <AlertCircle size={40} className="text-white/20" />
                </div>
                <h2 className="text-2xl font-serif font-bold mb-2">Sign in to view bills</h2>
                <p className="text-white/40 mb-8 max-w-xs text-sm">You need to be logged in to access your billing history and make payments.</p>
                <Button onClick={() => navigate("/login")} className="px-10 h-14 rounded-2xl bg-gold text-background font-bold">Sign In Now</Button>
            </div>
        );
    }

    return (
        <div className="min-h-screen pt-12 px-8 pb-32 mandala-pattern bg-background">
            <header className="mb-10 flex items-center">
                <button onClick={() => navigate(-1)} className="mr-6 p-2 bg-white/5 rounded-xl text-white/50 hover:text-white transition-all">
                    <ChevronLeft size={24} />
                </button>
                <div>
                    <h1 className="text-4xl font-serif font-bold text-white tracking-tight">My <span className="text-gradient">Bills</span></h1>
                    <p className="text-white/30 text-[10px] font-bold tracking-[0.2em] uppercase">Manage your payments</p>
                </div>
            </header>

            <div className="space-y-6">
                <AnimatePresence>
                    {bills.length === 0 ? (
                        <motion.div
                            initial={{ opacity: 0, scale: 0.9 }}
                            animate={{ opacity: 1, scale: 1 }}
                            className="p-12 text-center bg-charcoal/20 border border-white/5 rounded-[2.5rem]"
                        >
                            <Receipt className="mx-auto text-white/5 mb-4" size={64} />
                            <h3 className="text-xl font-serif font-bold text-white/60">No pending bills</h3>
                            <p className="text-white/20 text-sm mt-2">Any bills generated by the admin will appear here.</p>
                        </motion.div>
                    ) : (
                        bills.map((bill, idx) => (
                            <motion.div
                                key={bill.id}
                                initial={{ opacity: 0, y: 20 }}
                                animate={{ opacity: 1, y: 0 }}
                                transition={{ delay: idx * 0.1 }}
                            >
                                <Card className={`overflow-hidden border-white/5 bg-charcoal/30 flex flex-col ${bill.status === 'paid' ? 'opacity-80' : ''}`}>
                                    <div className="p-6">
                                        <div className="flex justify-between items-start mb-6">
                                            <div className="flex items-center">
                                                <div className={`p-3 rounded-2xl mr-4 ${bill.status === 'paid' ? 'bg-green-500/10 text-green-500' : 'bg-saffron/10 text-saffron'}`}>
                                                    <Receipt size={24} />
                                                </div>
                                                <div>
                                                    <p className="text-[10px] text-white/30 font-bold uppercase tracking-widest mb-1">Bill Reference</p>
                                                    <p className="font-mono text-sm text-white/80">#{bill.id.slice(-8).toUpperCase()}</p>
                                                </div>
                                            </div>
                                            <div className={`px-3 py-1 rounded-full text-[10px] font-bold uppercase tracking-widest border ${bill.status === 'paid' ? 'bg-green-500/10 text-green-500 border-green-500/20' : 'bg-red-500/10 text-red-500 border-red-500/20'}`}>
                                                {bill.status}
                                            </div>
                                        </div>

                                        <div className="space-y-3 mb-6">
                                            {bill.items?.slice(0, 3).map((item, i) => (
                                                <div key={i} className="flex justify-between text-sm">
                                                    <span className="text-white/40">{item.quantity}x {item.name}</span>
                                                    <span className="text-white/60">₹{item.price * item.quantity}</span>
                                                </div>
                                            ))}
                                            {bill.items?.length > 3 && (
                                                <p className="text-[10px] text-white/20 italic">+{bill.items.length - 3} more items...</p>
                                            )}
                                        </div>

                                        <div className="pt-4 border-t border-white/5 flex justify-between items-end">
                                            <div>
                                                <p className="text-[10px] text-white/20 font-bold uppercase tracking-widest mb-1">Total Amount</p>
                                                <p className="text-3xl font-black text-gold font-sans">₹{bill.total}</p>
                                            </div>
                                            {bill.status === 'unpaid' ? (
                                                <Button
                                                    onClick={() => handlePayment(bill)}
                                                    className="h-12 px-6 rounded-xl bg-saffron text-black font-black flex items-center shadow-lg shadow-saffron/10 hover:shadow-saffron/25 active:scale-95 transition-all"
                                                >
                                                    <CreditCard size={18} className="mr-2" />
                                                    Pay Now
                                                </Button>
                                            ) : (
                                                <div className="flex items-center text-green-500 font-bold text-sm">
                                                    <CheckCircle2 size={18} className="mr-2" />
                                                    Paid
                                                </div>
                                            )}
                                        </div>
                                    </div>
                                    {bill.status === 'paid' && (
                                        <div className="bg-white/[0.02] px-6 py-3 flex items-center justify-between border-t border-white/5">
                                            <span className="text-[10px] text-white/20 font-bold uppercase tracking-widest">Transaction ID</span>
                                            <span className="text-[10px] font-mono text-white/40">{bill.paymentId || 'N/A'}</span>
                                        </div>
                                    )}
                                </Card>
                            </motion.div>
                        ))
                    )}
                </AnimatePresence>
            </div>
        </div>
    );
};

export default BillsPage;
